Andrelo - Topic 4 - DB creation approach
Andrelo9/java-bootcamp-2016 pull request #11
Opened 2017-07-31 17:26 UTC by Andrelo9

2017-07-31 17:30 UTC, mmassigoge-glb commented on MySqlFiles/HighSchool.sql
> +    CONSTRAINT students_fk FOREIGN KEY(assigned_course)
Check this foreign key, if you are trying to relate students with courses you should first analyze how many students are taking one course and how many courses is taking one student. Then you can model this using the right approach. Let me know the answers to prior questions please

2017-07-31 18:31 UTC, sebastian-garofalo requested changes

2017-07-31 18:31 UTC, sebastian-garofalo commented on MySqlFiles/HighSchool.sql
> +    dni_number char(8) UNIQUE NOT NULL,
This could be a number, why use chars?

2017-07-31 18:31 UTC, sebastian-garofalo commented on MySqlFiles/HighSchool.sql
> +    assigned_teacher varchar(255),
The assigned teacher should reference the teachers table primary key, that is an int

2017-08-02 13:55 UTC, mmassigoge-glb commented on MySqlFiles/HighSchool.sql
> +    course_id INT,
This should be a FK also..

2017-08-02 13:56 UTC, mmassigoge-glb commented on MySqlFiles/HighSchool.sql
> +    course_id INT,
this should be a FK also..

2017-08-04 17:07 UTC, merged